version: '3'
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - backend
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        environment:
            - MYSQL_HOST=host.docker.internal # This is the host name for connecting to the host machine
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=
            - MYSQL_DATABASE=hotel
